baseurl = "https://indiependente.dev"
title = "Francesco Farina"

DefaultContentLanguage = "en"
languageCode = "en-us"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "dracula"

rssLimit = 10 # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"



[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Francesco Farina"
  keywords = "homepage, blog, science, informatics, development, programming"
  
  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  justifyContent = false

  [params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/indiependente"

  [[params.social]]
    name = "github"
    url = "https://github.com/indiependente"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/indiependente"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/francesco-farina-0579a6147"

  [[params.social]]
    name = "email"
    url = "mailto:mail.farinafrancesco@gmail.com"


[languages]
  [languages.en]
    title = "Francesco Farina"
    homeSubtitle = "Pressing buttons to explore rabbit holes"
    keywords = "computer, science, informatics, programming, development"
    copyright = ""
    readOtherPosts = "Read other posts"

  [languages.it]
    title = "Francesco Farina"
    homeSubtitle = "Pressing buttons to explore rabbit holes"
    keywords = "computer, science, informatica, programmazione, sviluppo"
    copyright = ""
    readOtherPosts = "Leggi altri post"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[markup.goldmark.renderer]
  unsafe= true