baseurl = "https://indiependente.dev"
title = "indiependente"

DefaultContentLanguage = "en"
languageCode = "en-us"

theme = "PaperMod"

PygmentsCodeFences = true
PygmentsStyle = "dracula"

rssLimit = 10 # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[minify]
  disableXML = true
  minifyOutput = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  avatar = "https://res.cloudinary.com/indiependente/image/upload/f_auto,q_auto/v1/indiependente.dev/uwdxrdxwmgc3shz2jwe8"
  name = "Francesco Farina"
  bio = "Pressing buttons to explore rabbit holes"
  rss = true # show rss icon
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Francesco Farina"
  keywords = ["homepage", "blog", "computer science", "development", "programming"]
  
  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "auto"
  justifyContent = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

# profile-mode
  [params.profileMode]
    enabled = true # needs to be explicitly set
    title = "Francesco Farina"
    subtitle = "Pressing buttons to explore rabbit holes"
    imageUrl = "https://res.cloudinary.com/indiependente/image/upload/f_auto,q_auto/v1/indiependente.dev/uwdxrdxwmgc3shz2jwe8"
    imageWidth = 120
    imageHeight = 120
    # imageTitle = my image
    [[params.profileMode.buttons]]
      name= "Posts"
      url= "posts"
    [[params.profileMode.buttons]]
      name = "Tags"
      url = "tags"
  [params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/indiependente"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:francesco@indiependente.anonaddy.com"

  [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.social/@indiependente"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/indiependente"

  [[params.socialIcons]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/francesco-farina-0579a6147"

  [[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/indiependente.bsky.social"

[languages]
  [languages.en]
    title = "Francesco Farina"
    # homeSubtitle = "Pressing buttons to explore rabbit holes"
    # keywords = "computer, science, informatics, programming, development"
    copyright = ""
    # readOtherPosts = "Read other posts"

  [languages.it]
    title = "Francesco Farina"
    # homeSubtitle = "Pressing buttons to explore rabbit holes"
    # keywords = "computer, science, informatica, programmazione, sviluppo"
    copyright = ""
    # readOtherPosts = "Leggi altri post"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

[markup.goldmark.renderer]
  unsafe= true
