[build] 
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.125.7"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.22.3"


[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.7"
  GO_VERSION = "1.22.3"
