[build] 
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.132.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.22.6"


[context.deploy-preview.environment]
  HUGO_VERSION = "0.132.1"
  GO_VERSION = "1.22.6"
